export const GET_USERS = 'GET_USERS';
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_REQUESTED = 'ADD_USER_REQUESTED';
export const ADD_USER_REJECTED = 'ADD_USER_REJECTED';
export const ADD_USER_FULFILLED = 'ADD_USER_FULFILLED';
